# .github/workflows/build-for-testing.yml
name: Build and Test for Manual Download

on:
  workflow_dispatch:

x-setup-steps: &setup_steps
  - name: Checkout repository
    uses: actions/checkout@v3
  - name: Set up JDK 11
    uses: actions/setup-java@v3
    with:
      distribution: 'temurin'
      java-version: '11'
  - name: Cache Gradle packages
    uses: actions/cache@v3
    with:
      path: |
        ~/.gradle/caches
        ~/.gradle/wrapper
      key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      restore-keys: |
        ${{ runner.os }}-gradle-
  - name: Grant execute permission to gradlew
    run: chmod +x ./gradlew

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - <<: *setup_steps

      - name: Run unit tests
        run: ./gradlew :app:test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: app/build/reports/tests/testReleaseUnitTest/

      - name: Build App Bundle (Release)
        run: ./gradlew :app:bundleRelease

      - name: Upload App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-bundle-release
          path: app/build/outputs/bundle/release/app-release.aab
